name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push docs to gh-pages
        run: ./deploy.sh
        if:  ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
